FROM nginx:1.13.3

COPY ./environments/development/conf/nginx/sites/default.conf /etc/nginx/conf.d/
COPY ./environments/development/conf/nginx/nginx.conf /etc/nginx/

ENV TZ=America/Sao_Paulo
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
